# Non-secret project-wide Gradle settings (safe to commit)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.incremental=true
